### PR TITLE
Upgrade from EOL node v8

### PR DESCRIPTION
**Pull request by ocxo**
Depends on https://github.com/articulate/docker-articulate-node/pull/60

NodeJS v6 and v8 are end of life. No security patches or bug fixes will be released for these versions.

https://nodejs.org/en/about/releases/

### CODE REVIEW

**Comment by tecnobrat** [comment]
Are these being used anywhere?

**Comment by ocxo** [comment]
TBH I'm at the point where I don't care if they are because teams have been given months of notice and Node 8 is EOL 🙃

**Comment by ocxo** [comment]
This is the list of remaining PRs to upgrade Node that haven't yet been merged https://github.com/pulls?q=is%3Apr+author%3Aocxo+archived%3Afalse+node+eol+is%3Aopen

**Comment by tecnobrat** [comment]
Mission control keeps track of the images that services are using.  We can check there.

**Comment by tecnobrat** [comment]
The problem is if we merge this, then platform-helpers is going to get complaints that teams builds are failing, it will fail in a weird way.  Which then puts more load on our team.  I feel like we should give the teams that need to update their images a final "We're going to merge this EOD on Monday, your builds will fail."

I would feel weird about just merging this and putting the extra load on the platform-helpers group.

**Comment by ocxo** [comment]
👍 I'm going to announce that

**Review by brittanydionigi — APPROVED** [review]

**Pull request merged**
